// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB1t4KUNoGO7Hq5Mw2RkeJBxd_CpayxTM',
    appId: '1:62074302175:web:0f1375bc4b86ba6b1b436a',
    messagingSenderId: '62074302175',
    projectId: 'chat-tutorial-bd6a0',
    authDomain: 'chat-tutorial-bd6a0.firebaseapp.com',
    storageBucket: 'chat-tutorial-bd6a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKb-eEUu8yujz5oQaOXIZr3PYO0Gx0tLs',
    appId: '1:62074302175:android:e2c52e9d3a2515f41b436a',
    messagingSenderId: '62074302175',
    projectId: 'chat-tutorial-bd6a0',
    storageBucket: 'chat-tutorial-bd6a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC80mYFDEuFGixLwh4Zb60oGjkGxDB9juc',
    appId: '1:62074302175:ios:9ad857fd564b69881b436a',
    messagingSenderId: '62074302175',
    projectId: 'chat-tutorial-bd6a0',
    storageBucket: 'chat-tutorial-bd6a0.firebasestorage.app',
    iosBundleId: 'com.example.chatTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC80mYFDEuFGixLwh4Zb60oGjkGxDB9juc',
    appId: '1:62074302175:ios:9ad857fd564b69881b436a',
    messagingSenderId: '62074302175',
    projectId: 'chat-tutorial-bd6a0',
    storageBucket: 'chat-tutorial-bd6a0.firebasestorage.app',
    iosBundleId: 'com.example.chatTutorial',
  );
}
